//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablePlanning.Models.CallNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimetablePlanning.Models.CallNotes.Resources.Notes", typeof(Notes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulate loco..
        /// </summary>
        internal static string CirculateLoco {
            get {
                return ResourceManager.GetString("CirculateLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect loco from staging area..
        /// </summary>
        internal static string CollectLocoFromStagingArea {
            get {
                return ResourceManager.GetString("CollectLocoFromStagingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect loco.
        /// </summary>
        internal static string ConnectLoco {
            get {
                return ResourceManager.GetString("ConnectLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect wagon groups.
        /// </summary>
        internal static string ConnectWagonGroups {
            get {
                return ResourceManager.GetString("ConnectWagonGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect wagons to.
        /// </summary>
        internal static string ConnectWagonsTo {
            get {
                return ResourceManager.GetString("ConnectWagonsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect loco.
        /// </summary>
        internal static string DisconnectLoco {
            get {
                return ResourceManager.GetString("DisconnectLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect wagon groups.
        /// </summary>
        internal static string DisconnectWagonGroups {
            get {
                return ResourceManager.GetString("DisconnectWagonGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect wagons to.
        /// </summary>
        internal static string DisconnectWagonsTo {
            get {
                return ResourceManager.GetString("DisconnectWagonsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive loco to staging area..
        /// </summary>
        internal static string DriveToStagingArea {
            get {
                return ResourceManager.GetString("DriveToStagingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid note configuration:.
        /// </summary>
        internal static string InvalidNoteConfiguration {
            get {
                return ResourceManager.GetString("InvalidNoteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meets.
        /// </summary>
        internal static string Meets {
            get {
                return ResourceManager.GetString("Meets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passes.
        /// </summary>
        internal static string Passes {
            get {
                return ResourceManager.GetString("Passes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn loco..
        /// </summary>
        internal static string TurnLoco {
            get {
                return ResourceManager.GetString("TurnLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turnus.
        /// </summary>
        internal static string Turnus {
            get {
                return ResourceManager.GetString("Turnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wagons.
        /// </summary>
        internal static string Wagons {
            get {
                return ResourceManager.GetString("Wagons", resourceCulture);
            }
        }
    }
}
